In [1]:
import torch
import torchvision

In [46]:
print(f"PyTorch version: {torch.__version__}")
print(f"Torchvision version: {torchvision.__version__}")
print(f"is CUDA available? {torch.cuda.is_available()}")

PyTorch version: 1.2.0
Torchvision version: 0.4.0a0+6b959ee
is CUDA available? False


In [34]:
# create a matrix with random values
x = torch.rand(5, 3)
x

tensor([[0.5344, 0.2444, 0.0513],
        [0.5381, 0.1539, 0.4347],
        [0.5833, 0.0382, 0.4653],
        [0.1051, 0.7104, 0.0907],
        [0.4441, 0.3133, 0.5929]])

In [35]:
x.size()

torch.Size([5, 3])

In [36]:
# create a matrix containing only zeros, and define the element's type as long
x = torch.zeros(5, 3, dtype=torch.long)
x

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [37]:
# a tensor can also be contructed directly from a list/array
x = torch.tensor([5.3, 7, 9.2], dtype=torch.double)
x

tensor([5.3000, 7.0000, 9.2000], dtype=torch.float64)

In [38]:
# create new tensors based on existing ones. 
# The new tensor inherits the properties from the originating tensor, 
# except for the specified properties. 
# We need to specify the size of the new tensor.
# For example, the next line
# creates a tensor of long values based on the tensor x
y = x.new_ones(5, 3, dtype=torch.long) # override dtype property
y

tensor([[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]])

In [39]:
y = torch.randn_like(x, dtype=torch.float)
y # same shape, different dtype and values

tensor([ 1.1844, -0.6977,  1.0336])

In [40]:
y.size()

torch.Size([3])

In [41]:
# to access the value of a 1-element tensor, use item method
x = torch.randn(1)
print(x)
print(x.item())


tensor([0.5152])
0.5152357816696167


In [43]:
# Using torch tensors and numpy arrays to reference the same object
a = torch.ones(5)
a

tensor([1., 1., 1., 1., 1.])

In [44]:
b = a.numpy()
b # 'b' is a reference to the same memory location as 'a'

array([1., 1., 1., 1., 1.], dtype=float32)

In [45]:
a.add_(1) # in-place addition, which also change b
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [48]:
# Using a NumPy array through a Torch tensor. 
import numpy as np
a  = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
# Since both np array 'a' and tensor 'b' share the same underlying memory location, 
# the addition should change both
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [51]:
# Using CUDA Tensors
# Tensors can be moved to any device using the `.to` method

# So, if running on a CUDA enabled computer....
if torch.cuda.is_available():
    device = torch.device('cuda')
    y = torch.ones_like(x, device=device)    # create the tensor directly on the GPU
    x = x.to(device)                         
    z = x + y
    print(z)
    print(z.to('cpu', torch.double))         # override dtype while calling `.to`
    
# The expected output, in case GPU is available:
# > tensor([3.9926], device='cuda:0')
# > tensor([3.9926], dtype=torch.float64)


In [52]:
# Autograd package functionalities
x = torch.ones(2,2, requires_grad=True)
x

tensor([[1., 1.],
        [1., 1.]], requires_grad=True)

In [53]:
y = x + 2
y

tensor([[3., 3.],
        [3., 3.]], grad_fn=<AddBackward0>)

In [56]:
z = y * y * 4
out = z.mean()
print(z, out)

tensor([[36., 36.],
        [36., 36.]], grad_fn=<MulBackward0>) tensor(36., grad_fn=<MeanBackward0>)


In [57]:
out.backward() # out contains a single scalar. Thus, .backward() is equivalent to out.backward(torch.tensor(1.))

In [58]:
# now print the gradients d(out)/dx:
print(x.grad)

tensor([[6., 6.],
        [6., 6.]])
